batch_size: 256
enable_non_negativity_constraint: false
enable_sparsity_loss: true
enable_wandb: true
enable_weight_decay_loss: true
input_dim: 64
sparsity_factor: 0.05
sparsity_loss_coef: 0.001
weight_decay: 0.001
window_size: 1
