batch_size: 64
enable_non_negativity_constraint: true
enable_sparsity_loss: false
enable_wandb: true
enable_weight_decay_loss: false
input_dim: 70
sparsity_factor: 0.005
sparsity_loss_coef: 0.001
weight_decay: 0.001
window_size: 1
